### ISSUE TITLE
tz and time

### ISSUE THREAD

**Issue by boelle** [santoshphilip/pyephem_sunpath#1]
i tried to google and never found an answer so hop its ok to ask here

but is tz the amount of hours in relation to UTC?

and would this use the current time?

thetime = datetime.now()

my code is:

> from pyephem_sunpath.sunpath import sunpos
> from datetime import datetime
> 
> thetime = datetime.now()
> lat = 55.327013
> lon = 10.438298
> tz = 2
> 
> alt, azm = sunpos(thetime, lat, lon, tz, dst=False)
> print(alt, azm)
> print(datetime.now())

**Comment by santoshphilip** [comment]
The easiest way to find the time zone for a place is to google for it.

if you google "time zone for new york" you get::

    Time zone in New York, NY (GMT-4)

time zone for new york is -4

    
if you google "time zone for india" you get::

    Time zone in India (GMT+5:30)

time zone for india is +5.5

thetime is local. So you need to find the time in New york or inda as the case may be.

datetime.now() will depend on the time zone your computer is set for. So if you are in New York, it will give you the local time in New York. (assuming your computer time is set for New york)


Having said all that, I think there is some bug in the function. It is not giving the same results as the NOAA web site https://www.esrl.noaa.gov/gmd/grad/solcalc/azel.html (or I am tired and sleep and may be doing something wrong :-(

**Comment by boelle** [comment]
my raspberry pi is set for local time and i did check the results against the site https://www.suncalc.org
it stays pretty much the same

now i just need to adjust my pool monitor code so that the pump for solar heating starts when the sun is up

but so far it looks like this

![image](https://user-images.githubusercontent.com/3832239/61279785-108c6180-a7b7-11e9-8389-323cf0d76c7c.png)

its amazing what astronomy can be used for :-D

**Comment by santoshphilip** [comment]
interesting use for pyephem_sunpath. This is the first time I am seeing it used with hardware.
Are you triggering the pump for sun rise or waiting until the sun gets above a certain altitude ?
(I think there is a function for sunrise time)

**Comment by boelle** [comment]
one trigger will be when sunangle or altitude is above 0... ie when the sun is above horizon
but then i will also wait for temp in top of the solar system to rise, 

no need to turn on the pump if its a clouded day with no sun heating it

and then my off trigger will be when sun is below horizon and heat from the solar system is dropping below that of the pool itself

**Comment by santoshphilip** [comment]
@boelle , I am going to close this issue as resolved.
If you run into anything else, go ahead and open a new issue
